### ISSUE TITLE
Fail package is busted on hackage 

### ISSUE THREAD

**Issue by cartazio** [haskell-infra/hackage-trustees#146] opened 2018-03-23 20:17 UTC
https://matrix.hackage.haskell.org/package/fail

Not sure what’s up 

@hvr?

**Comment by hvr** [comment] 2018-03-23 21:00
cc @alexbiehl

**Comment by hvr** [comment] 2018-03-25 21:55
Duplicate of haskell/cabal#5232

**Closed by hvr** 2018-03-25 21:55 UTC

**Comment by cartazio** [comment] 2018-04-17 23:33
@hvr is bytestring-builder another package which will make haddock fail?
