### ISSUE TITLE
Address the bug in recent versions of clock

### ISSUE THREAD

**Issue by mightybyte** [haskell-infra/hackage-trustees#63] opened 2016-03-24 12:49 UTC
It seems that this issue in the clock package is being felt by more and more people and @hvr suggested that I report it here.

https://github.com/corsis/clock/issues/36

The issue has been open for 3 months with no response from the maintainer.  I've also sent personal emails and still no response, so we might want to think about addressing it at this level.

The bug is quite critical.  Anything that calls `fromInteger` on a TimeSpec will just die.  As the issue mentions, we ran into it with Snap 1.0 and it was rather difficult to debug.

I don't know what the right solution is.  Perhaps we could just deprecate all the offending versions on hackage.  I suppose a package takeover or fork are also options.  But we would need to find a maintainer willing to take on this somewhat hairy low level code and its cross-platform compatibility.

**Comment by bergmark** [comment] 2016-03-25 16:36
I think the best option here is to do a non-maintainer upload to resolve the issue without having to find a new maintainer. We can also deprecate the offending versions but deprecation is a weak constraint so those versions are still somewhat likely to be picked unless there is a later version.

Would re-introducing the old `fromInteger` be a valid patch? I don't see any explanation why it was removed in the first place.

**Comment by mightybyte** [comment] 2016-03-25 18:04
That seems like a reasonable solution as far as I'm concerned.

**Comment by bergmark** [comment] 2016-03-31 12:17
- [x] (Anyone) Send a pull request or open an issue to the offending packages source repository. If no source repository is available, send an e-mail.
- [x] (Anyone) After a while if there is no response, open a ticket in the trustees issue tracker, linking to the pull request / issue, or describing/embedding the e-mail. Alternatively if problems are anticipated from the outset then file the issue immediately.
- [x] (Trustee) When the issue is opened, a trustee must try to contact the maintainer(s), primarily by e-mail to try and resolve things without needing to force anything. They must record in the ticket when they first tried to contact the maintainer(s). This documents the start of the 2-week deadline. (Many users do not have github notifications set up.)
- [ ] (Trustee) After a week if there's still no contact with any of the maintainers then a trustee should again email the maintainers to inform them of the plan to do a NMU, what, why and when. The when is at earliest in a week. The trustee must record in the ticket when again tried to contact the maintainer(s). This documents the start of the 1-week deadline.
- [ ] (Anyone) Discuss exactly what code needs to be changed.
- [ ] (Trustee) Fork the upstream repo under the hackage-trustee organisation on github and prepare the patches (perhaps by pulling in changes from somewhere else), including a tag.
- [ ] (Trustee) Get at least a second trustee to look at and agree to the changes for the proposed NMU.
- [ ] (Admin) After the deadline (no sooner than 2 weeks from the original contact attempt and no sooner than 1 week from the contact attempt where the intention to do a NMU is explained), and having got signoff from two trustees, an admin may grant the trustees authority to make uploads for the package in question.
- [ ] (Trustee) Tag the version to be uploaded. Do the NMU. Again inform the maintainers about what has happened and where they can see the changes that have been made (ie the forked repo and the ticket tracking the issue).

**Comment by cetinsert** [comment] 2016-04-05 08:05
I am now going to re-introduce fromInteger in the next few minutes. We could then discuss whether the Num instace for TimeSpec makes sense as it does not behave as one would expect in certain cases.

**Comment by cetinsert** [comment] 2016-04-05 08:28
`fromInteger` has been reintroduced in 0.7.1.1, package uploaded to hackage.

Now how could we address the clock issues [#32](https://github.com/corsis/clock/issues/32) and [#33](https://github.com/corsis/clock/issues/33)?

**Comment by bergmark** [comment] 2016-04-05 14:28
@cetinsert thank you! I think what @lfairy suggests in https://github.com/corsis/clock/issues/32#issuecomment-205721443 is a good way to proceed. I'll close this in favor of tickets on your issue tracker.

**Closed by bergmark** 2016-04-05 14:28 UTC
Labels: NMU
