### ISSUE TITLE
Latest Lens and WAI stack conflict over primitive.

### ISSUE THREAD

**Issue by RayRacine** [haskell-infra/hackage-trustees#10] opened 2015-03-31 13:47 UTC
Latest WAI stack requires primitive 0.6, while most recent Lens has upper bound of primitive <0.6

trying: wai-app-static-3.0.0.6 
trying: cryptohash-conduit-0.1.1 (dependency of wai-app-static-3.0.0.6)
trying: conduit-extra-1.1.7.1 (dependency of cryptohash-conduit-0.1.1)
trying: primitive-0.6 (dependency of conduit-extra-1.1.7.1)
...
rejecting: lens-4.8 (conflict: primitive==0.6, lens => primitive>=0.4.0.1 &&
<0.6)

**Comment by cartazio** [comment] 2015-03-31 14:32
Sounds like a bug on wai.   Lens hasn't cut a 0.6 release yet, though
though master has support already.  4.9 will support 0.6

**Comment by bergmark** [comment] 2015-03-31 14:56
@RayRacine please see https://github.com/haskell-infra/hackage-trustees/blob/master/CONTRIBUTING.md

So far this is not enough information for me to reproduce the issue.

I also don't see any package that requires `primitive >= 0.6`: http://packdeps.haskellers.com/reverse/primitive . Are you sure a package is introducing this constraint?

**Comment by bergmark** [comment] 2015-04-24 14:43
Since no further information has been supplied I'll close this. Please let us now if you think we should re-open.

**Closed by bergmark** 2015-04-24 14:43 UTC
