### ISSUE TITLE
hgettext needs NMU to support newer haskell-src-exts

### ISSUE THREAD

**Issue by clinty** [haskell-infra/hackage-trustees#105] opened 2017-06-22 02:52 UTC
https://github.com/vasylp/hgettext/issues/10

dependency of bustle

**Comment by hvr** [comment] 2017-06-22 07:45
@clinty tbh, I can't confirm the bitrot. Cabal doesn't appear to run into unsound install-plans caused by `hgettext`'s meta-data for GHC < 8.2 (see https://matrix.hackage.haskell.org/package/hgettext).

As for GHC 8.2.1, once https://github.com/tibbe/hashable/pull/140#issuecomment-310300409 is resolved I expect GHC 8.2.1 to be fine too.

**Comment by clinty** [comment] 2017-06-22 14:39
It's the incompatibility with haskell-src-exts 1.18 that's the problem.  If this is out of scope for hackage-trustees, feel free to close.

**Comment by hvr** [comment] 2017-06-22 15:17
@clinty oh that! That's actually in-scope, it's just that we usually refer to bit-rotting for something totally else. This here is rather about requesting a non-maintainer-upload.

**Comment by jtojnar** [comment] 2017-12-15 23:51
What is the status of this NMU? It seems to be stuck on the second step of the procedure, is that right?

The pull request is here: https://github.com/vasylp/hgettext/pull/11

**Comment by hvr** [comment] 2017-12-17 22:10
Thanks for the reminder; expect a new release soon!

**Comment by hvr** [comment] 2017-12-29 22:50
@jtojnar sorry, I got side-tracked; it should be addressed by http://hackage.haskell.org/package/hgettext-0.1.31.0 now

**Closed by hvr** 2017-12-29 22:50 UTC
Labels: NMU
