### ISSUE TITLE
binary 0.8.7 doesn't allow ghc 8.6.3

### ISSUE THREAD

**Issue by cartazio** [haskell-infra/hackage-trustees#234] opened 2019-07-23 15:05 UTC
@hvr @23skidoo , i'm quite confused about what is happening here, i dont see any constraints...
```
$ cabal v2-install binary --dry
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: binary-0.8.7.0 (user goal)
[__1] next goal: ghc (user goal)
[__1] rejecting: ghc-8.6.5, ghc-8.6.4 (constraint from user target requires
==8.6.3)
[__1] rejecting: ghc-8.6.3/installed-8.6... (conflict: binary==0.8.7.0, ghc =>
binary==0.8.6.0/installed-0.8...)
[__1] rejecting: ghc-8.6.1, ghc-8.4.4, ghc-8.4.3, ghc-8.4.1, ghc-8.2.2,
ghc-8.2.1 (constraint from user target requires ==8.6.3)
[__1] fail (backjumping, conflict set: binary, ghc)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: binary, ghc

```

if this weren't v2, i'd be thinking that its about ghc needing binary 0.8.6.0 ..

**Comment by 23Skidoo** [comment] 2019-07-23 15:10
/cc @typedrat
I think it's because you're using install instead of build, so it tries to solve for a globally consistent package set, which includes ghc so that you could fire up ghci and be able to load both fix and binary.

**Comment by phadej** [comment] 2019-07-23 16:44
I'm quite sure this is duplicate of https://github.com/haskell/cabal/issues/5888 and https://github.com/haskell/cabal/issues/5559

I.e. after `v2-install --lib` things go bananas.

**Closed by phadej** 2019-07-23 16:44 UTC

**Comment by cartazio** [comment] 2019-07-23 17:41
Gotcha on global consistency

So there’s probably some better error info about this that could be
presented so users know it’ll be fine as a build dep
